const CONTENT_TYPE_APPLICATION_ZIP = 'application/zip';
const ACL_PRIVATE = 'private';
const OPEN = 'open';
const ERROR = 'error';
const USER_LOGS_S3_BUCKET_NAME='test44441'; // TODO this bucket will be created programmatically
const LAMBDA_DEPLOYMENT_PACKAGE_S3_BUCKET_NAME='rehydrate-lambda-dep-pkg';
const REHYDRATION_LAMBDA_NAME='RehydrateLambda';
const REHYDRATION_QUEUE_NAME='RehydrateSQS';
const STATUS_QUEUE_NAME='StatusSQS';
const REHYDRATION_DLQ='RehydrateSQSDLQ';
const STATUS_DLQ='StatusSQSDLQ';

const REHYDRATE_LAMBDA_ROLE_NAME='rehydrate-lambda-role';
const TIMEOUT_LENGTH_IN_MILLIS = 30 * 1000;

export {
  CONTENT_TYPE_APPLICATION_ZIP,
  ACL_PRIVATE,
  OPEN,
  ERROR,
  USER_LOGS_S3_BUCKET_NAME,
  LAMBDA_DEPLOYMENT_PACKAGE_S3_BUCKET_NAME,
  REHYDRATION_LAMBDA_NAME,
  REHYDRATION_QUEUE_NAME,
  REHYDRATE_LAMBDA_ROLE_NAME,
  TIMEOUT_LENGTH_IN_MILLIS,
  STATUS_QUEUE_NAME,
  REHYDRATION_DLQ,
  STATUS_DLQ
}